# Generated by Django 4.2.30 on 2026-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
